import type { SurveyFormData } from '../temp'

export const EDIT_SURVEY_DATA: SurveyFormData = {
    name: 'Matchday experience survey',
    description: 'Help us improve the stadium and matchday experience.',
    thankYouMessage: 'Thank you for sharing your feedback with us.',
    expireDate: '2026-09-30',
    sharePublicly: true,
    linkValidity: 30,
    shareEmails: ['marketing@relatoo.cz', 'support@relatoo.cz'],
    color: '#7EC71E',
    multiple: false,
    showLogo: true,
    sections: [
        {
            id: 'section-1',
            name: 'Overall experience',
            questions: [
                {
                    id: 'question-1',
                    name: 'How would you rate your overall experience?',
                    description: 'Rate the complete matchday experience.',
                    type: 'rating',
                    required: true,
                    starCount: 5,
                    rateCount: 5,
                    textStart: '',
                    textEnd: '',
                    rows: ['Row 1'],
                    columns: ['Column 1', 'Column 2'],
                    checkMoreOptions: false,
                    selectionOptions: [
                        {
                            id: 'option-1',
                            label: 'Option 1',
                            allowSecondaryText: false,
                            secondaryTextRequired: false,
                        },
                        {
                            id: 'option-2',
                            label: 'Option 2',
                            allowSecondaryText: false,
                            secondaryTextRequired: false,
                        },
                    ],
                    multipleSelection: false,
                },
                {
                    id: 'question-2',
                    name: 'How likely are you to visit again?',
                    description: 'Select a value on the scale.',
                    type: 'linear-scale',
                    required: true,
                    starCount: 5,
                    rateCount: 8,
                    textStart: 'Not likely',
                    textEnd: 'Very likely',
                    rows: ['Row 1'],
                    columns: ['Column 1', 'Column 2'],
                    checkMoreOptions: false,
                    selectionOptions: [],
                    multipleSelection: false,
                },
            ],
        },
        {
            id: 'section-2',
            name: 'Services and facilities',
            questions: [
                {
                    id: 'question-1',
                    name: 'Which services did you use?',
                    description: 'You can choose from the available options.',
                    type: 'selection',
                    required: false,
                    starCount: 5,
                    rateCount: 5,
                    textStart: '',
                    textEnd: '',
                    rows: ['Row 1'],
                    columns: ['Column 1', 'Column 2'],
                    checkMoreOptions: false,
                    selectionOptions: [
                        {
                            id: 'option-1',
                            label: 'Refreshments',
                            allowSecondaryText: false,
                            secondaryTextRequired: false,
                        },
                        {
                            id: 'option-2',
                            label: 'Fan shop',
                            allowSecondaryText: false,
                            secondaryTextRequired: false,
                        },
                        {
                            id: 'option-3',
                            label: 'Other',
                            allowSecondaryText: true,
                            secondaryTextRequired: false,
                        },
                    ],
                    multipleSelection: true,
                },
            ],
        },
    ],
}
